2025-01-15 11:20:40 - recieved ip and port from server: ('172.16.20.119', '3102')
2025-01-15 11:20:41 - Login was succesfull for user: a
2025-01-15 11:20:41 - File data recieved 0
2025-01-15 11:20:41 - Profile picture was recieved
2025-01-15 11:20:41 - Got files
2025-01-15 11:20:41 - Current used storage is 74.808
2025-01-15 11:20:41 - Got directories
2025-01-15 11:22:28 - recieved ip and port from server: ('172.16.20.119', '3102')
2025-01-15 11:22:28 - Login was succesfull for user: a
2025-01-15 11:22:29 - File data recieved 0
2025-01-15 11:22:29 - Profile picture was recieved
2025-01-15 11:22:29 - Got files
2025-01-15 11:22:29 - Current used storage is 74.808
2025-01-15 11:22:29 - Got directories
2025-01-15 11:24:51 - recieved ip and port from server: ('172.16.20.119', '3102')
2025-01-15 11:24:52 - Login was succesfull for user: a
2025-01-15 11:24:52 - File data recieved 0
2025-01-15 11:24:52 - Profile picture was recieved
2025-01-15 11:24:52 - Got files
2025-01-15 11:24:52 - Current used storage is 74.808
2025-01-15 11:24:52 - Got directories
2025-01-15 12:22:24 - recieved ip and port from server: ('192.168.56.1', '3102')
2025-01-15 12:22:26 - recieved ip and port from server: ('192.168.56.1', '3102')
2025-01-15 12:22:48 - recieved ip and port from server: ('192.168.56.1', '3102')
2025-01-15 12:22:50 - recieved ip and port from server: ('192.168.56.1', '3102')
2025-01-15 12:28:16 - recieved ip and port from server: ('172.16.20.119', '3102')
2025-01-15 12:28:16 - Login was succesfull for user: a
2025-01-15 12:28:16 - File data recieved 0
2025-01-15 12:28:16 - Profile picture was recieved
2025-01-15 12:28:16 - Current used storage is 74.808
2025-01-15 12:28:16 - Got files
2025-01-15 12:28:16 - Got directories
2025-01-15 12:28:29 - No server found
2025-01-15 12:28:34 - No server found
2025-01-15 12:29:14 - No server found
2025-01-15 12:29:19 - No server found
2025-01-15 12:30:02 - No server found
2025-01-15 12:30:08 - No server found
2025-01-15 12:34:01 - No server found
2025-01-15 12:34:06 - No server found
2025-01-15 12:35:07 - No server found
2025-01-15 12:35:12 - No server found
2025-01-15 12:36:44 - No server found
2025-01-15 12:36:49 - No server found
2025-01-15 12:38:55 - No server found
2025-01-15 12:39:00 - No server found
2025-01-15 12:39:37 - No server found
2025-01-15 12:39:42 - No server found
2025-01-15 12:52:44 - No server found
2025-01-15 12:52:49 - No server found
2025-01-15 12:57:37 - recieved ip and port from server: ('172.16.20.119', '3102')
2025-01-15 12:57:37 - Login was succesfull for user: a
2025-01-15 12:57:38 - File data recieved 0
2025-01-15 12:57:38 - Profile picture was recieved
2025-01-15 12:57:38 - Current used storage is 74.808
2025-01-15 12:57:38 - Got files
2025-01-15 12:57:38 - Got directories
2025-01-15 13:10:50 - recieved ip and port from server: ('172.16.20.119', '3102')
2025-01-15 13:10:50 - Login was succesfull for user: a
2025-01-15 13:10:50 - File data recieved 0
2025-01-15 13:10:50 - Profile picture was recieved
2025-01-15 13:10:50 - Current used storage is 74.808
2025-01-15 13:10:50 - Got files
2025-01-15 13:10:50 - Got directories
2025-01-15 13:10:52 - Logout succesfull
2025-01-15 13:12:04 - recieved ip and port from server: ('172.16.20.119', '3102')
2025-01-15 13:12:05 - Login was succesfull for user: a
2025-01-15 13:12:05 - File data recieved 0
2025-01-15 13:12:05 - Profile picture was recieved
2025-01-15 13:12:05 - Got files
2025-01-15 13:12:05 - Current used storage is 74.808
2025-01-15 13:12:05 - Got directories
2025-01-15 13:15:06 - recieved ip and port from server: ('172.16.20.119', '3102')
2025-01-15 13:15:06 - Login was succesfull for user: a
2025-01-15 13:15:06 - File data recieved 0
2025-01-15 13:15:06 - Profile picture was recieved
2025-01-15 13:15:06 - Got files
2025-01-15 13:15:06 - Current used storage is 74.808
2025-01-15 13:15:06 - Got directories
2025-01-15 13:20:24 - Traceback (most recent call last):
  File "C:\Users\idanh\Desktop\Cyber\My Projects\Final-Project\Main\client\client.pyw", line 1962, in search_server
    netmask = get_subnet_mask()  # Adjust based on your network configuration
              ^^^^^^^^^^^^^^^^^
  File "C:\Users\idanh\Desktop\Cyber\My Projects\Final-Project\Main\client\client.pyw", line 1953, in get_subnet_mask
    if addr.family == psutil.AF_INET and addr.address != '127.0.0.1':  # Ignore localhost
                      ^^^^^^^^^^^^^^
AttributeError: module 'psutil' has no attribute 'AF_INET'
2025-01-15 13:20:26 - Traceback (most recent call last):
  File "C:\Users\idanh\Desktop\Cyber\My Projects\Final-Project\Main\client\client.pyw", line 1915, in connect_server
    sock.connect((ip, int(port)))
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\idanh\Desktop\Cyber\My Projects\Final-Project\Main\client\client.pyw", line 1962, in search_server
    netmask = get_subnet_mask()  # Adjust based on your network configuration
              ^^^^^^^^^^^^^^^^^
  File "C:\Users\idanh\Desktop\Cyber\My Projects\Final-Project\Main\client\client.pyw", line 1953, in get_subnet_mask
    if addr.family == psutil.AF_INET and addr.address != '127.0.0.1':  # Ignore localhost
                      ^^^^^^^^^^^^^^
AttributeError: module 'psutil' has no attribute 'AF_INET'
2025-01-15 13:20:39 - Traceback (most recent call last):
  File "c:\Users\idanh\Desktop\Cyber\My Projects\Final-Project\Main\client\client.pyw", line 1962, in search_server
    netmask = get_subnet_mask()  # Adjust based on your network configuration
              ^^^^^^^^^^^^^^^^^
  File "c:\Users\idanh\Desktop\Cyber\My Projects\Final-Project\Main\client\client.pyw", line 1953, in get_subnet_mask
    if addr.family == psutil.AF_INET and addr.address != '127.0.0.1':  # Ignore localhost
                      ^^^^^^^^^^^^^^
AttributeError: module 'psutil' has no attribute 'AF_INET'
2025-01-15 13:20:41 - Traceback (most recent call last):
  File "c:\Users\idanh\Desktop\Cyber\My Projects\Final-Project\Main\client\client.pyw", line 1915, in connect_server
    sock.connect((ip, int(port)))
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\idanh\Desktop\Cyber\My Projects\Final-Project\Main\client\client.pyw", line 1962, in search_server
    netmask = get_subnet_mask()  # Adjust based on your network configuration
              ^^^^^^^^^^^^^^^^^
  File "c:\Users\idanh\Desktop\Cyber\My Projects\Final-Project\Main\client\client.pyw", line 1953, in get_subnet_mask
    if addr.family == psutil.AF_INET and addr.address != '127.0.0.1':  # Ignore localhost
                      ^^^^^^^^^^^^^^
AttributeError: module 'psutil' has no attribute 'AF_INET'
2025-01-15 13:24:34 - recieved ip and port from server: ('172.16.20.119', '3102')
2025-01-15 13:24:34 - Login was succesfull for user: a
2025-01-15 13:24:34 - File data recieved 0
2025-01-15 13:24:34 - Profile picture was recieved
2025-01-15 13:24:34 - Got files
2025-01-15 13:24:34 - Current used storage is 74.808
2025-01-15 13:24:35 - Got directories
2025-01-15 13:27:52 - recieved ip and port from server: ('172.16.20.119', '3102')
2025-01-15 13:27:52 - Login was succesfull for user: a
2025-01-15 13:27:52 - File data recieved 0
2025-01-15 13:27:52 - Profile picture was recieved
2025-01-15 13:27:52 - Current used storage is 74.808
2025-01-15 13:27:52 - Got files
2025-01-15 13:27:52 - Got directories
